version: '3'

services:
  pontua-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: pontua-challenge-image
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: yarn start
